// <auto-generated />
using System;
using Microservicio.Vuelos.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Microservicio.Vuelos.DataAccess.Migrations
{
    [DbContext(typeof(SistemaVuelosDbContext))]
    [Migration("20260501024210_InitPostgres")]
    partial class InitPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.AeropuertoEntity", b =>
                {
                    b.Property<int>("IdAeropuerto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_aeropuerto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAeropuerto"));

                    b.Property<string>("CodigoIata")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("codigo_iata");

                    b.Property<string>("CodigoIcao")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("codigo_icao");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<int>("IdCiudad")
                        .HasColumnType("integer")
                        .HasColumnName("id_ciudad");

                    b.Property<int>("IdPais")
                        .HasColumnType("integer")
                        .HasColumnName("id_pais");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitud");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('00000001','hex')");

                    b.Property<string>("ZonaHoraria")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zona_horaria");

                    b.HasKey("IdAeropuerto");

                    b.HasIndex("CodigoIata")
                        .IsUnique()
                        .HasDatabaseName("UQ_AEROPUERTO_CODIGO_IATA");

                    b.HasIndex("IdCiudad");

                    b.HasIndex("IdPais");

                    b.ToTable("AEROPUERTO", "aero");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.AsientoEntity", b =>
                {
                    b.Property<int>("IdAsiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_asiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAsiento"));

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clase");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("disponible");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<int>("IdVuelo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vuelo");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("NumeroAsiento")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("numero_asiento");

                    b.Property<string>("Posicion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("posicion");

                    b.Property<decimal>("PrecioExtra")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_extra");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('00000001','hex')");

                    b.HasKey("IdAsiento");

                    b.HasIndex("IdVuelo", "NumeroAsiento")
                        .IsUnique()
                        .HasDatabaseName("UQ_ASIENTO_VUELO_NUMERO");

                    b.ToTable("ASIENTO", "vuelos");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.AuditoriaLogEntity", b =>
                {
                    b.Property<long>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_auditoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdAuditoria"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<Guid>("AuditoriaGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("auditoria_guid");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("text")
                        .HasColumnName("datos_anteriores");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("text")
                        .HasColumnName("datos_nuevos");

                    b.Property<DateTime>("FechaEventoUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_evento_utc");

                    b.Property<string>("IdRegistroAfectado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_registro_afectado");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_origen");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operacion");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('00000001','hex')");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tabla_afectada");

                    b.Property<string>("UsuarioEjecutor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_ejecutor");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("AuditoriaGuid")
                        .IsUnique()
                        .HasDatabaseName("UQ_AUDITORIA_GUID");

                    b.HasIndex("FechaEventoUtc")
                        .HasDatabaseName("IX_AUDITORIA_FECHA");

                    b.HasIndex("TablaAfectada")
                        .HasDatabaseName("IX_AUDITORIA_TABLA");

                    b.ToTable("AUDITORIA_LOG", "crm");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.BoletoEntity", b =>
                {
                    b.Property<int>("IdBoleto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_boleto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBoleto"));

                    b.Property<decimal>("CargoEquipaje")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cargo_equipaje");

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clase");

                    b.Property<string>("CodigoBoleto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_boleto");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("es_eliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoBoleto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_boleto");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<int?>("IdAsiento")
                        .HasColumnType("integer")
                        .HasColumnName("id_asiento");

                    b.Property<int>("IdFactura")
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    b.Property<int>("IdReserva")
                        .HasColumnType("integer")
                        .HasColumnName("id_reserva");

                    b.Property<int>("IdVuelo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vuelo");

                    b.Property<decimal>("ImpuestosBoleto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("impuestos_boleto");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<decimal?>("PrecioAsientoExtra")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_asiento_extra");

                    b.Property<decimal>("PrecioFinal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_final");

                    b.Property<decimal>("PrecioVueloBase")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_vuelo_base");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('00000001','hex')");

                    b.HasKey("IdBoleto");

                    b.HasIndex("CodigoBoleto")
                        .IsUnique()
                        .HasDatabaseName("UQ_BOLETO_CODIGO");

                    b.HasIndex("IdAsiento");

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdReserva");

                    b.HasIndex("IdVuelo");

                    b.ToTable("BOLETO", "ventas");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.CiudadEntity", b =>
                {
                    b.Property<int>("IdCiudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_ciudad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCiudad"));

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<int>("IdPais")
                        .HasColumnType("integer")
                        .HasColumnName("id_pais");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitud");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('00000001','hex')");

                    b.Property<string>("ZonaHoraria")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zona_horaria");

                    b.HasKey("IdCiudad");

                    b.HasIndex("IdPais", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_CIUDAD_PAIS_NOMBRE");

                    b.ToTable("CIUDAD", "aero");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.ClienteEntity", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<Guid>("ClienteGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_guid");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("es_eliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaInhabilitacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_inhabilitacion_utc");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("genero");

                    b.Property<int>("IdCiudadResidencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_ciudad_residencia");

                    b.Property<int>("IdPaisNacionalidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_pais_nacionalidad");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("MotivoInhabilitacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo_inhabilitacion");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nacionalidad");

                    b.Property<string>("Nombres")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero_identificacion");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("razon_social");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('00000001','hex')");

                    b.Property<string>("ServicioOrigen")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("servicio_origen");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_identificacion");

                    b.HasKey("IdCliente");

                    b.HasIndex("ClienteGuid")
                        .IsUnique()
                        .HasDatabaseName("UQ_CLIENTE_GUID");

                    b.HasIndex("Correo")
                        .HasDatabaseName("IX_CLIENTE_CORREO");

                    b.HasIndex("IdCiudadResidencia");

                    b.HasIndex("IdPaisNacionalidad");

                    b.HasIndex("NumeroIdentificacion")
                        .IsUnique()
                        .HasDatabaseName("UQ_CLIENTE_IDENTIFICACION");

                    b.ToTable("CLIENTES", "crm");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.EquipajeEntity", b =>
                {
                    b.Property<int>("IdEquipaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_equipaje");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEquipaje"));

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<string>("DescripcionEquipaje")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion_equipaje");

                    b.Property<string>("DimensionesCm")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dimensiones_cm");

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("es_eliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoEquipaje")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_equipaje");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<int>("IdBoleto")
                        .HasColumnType("integer")
                        .HasColumnName("id_boleto");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("NumeroEtiqueta")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_etiqueta");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("peso_kg");

                    b.Property<decimal>("PrecioExtra")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_extra");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('00000001','hex')");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("IdEquipaje");

                    b.HasIndex("IdBoleto");

                    b.HasIndex("NumeroEtiqueta")
                        .IsUnique()
                        .HasDatabaseName("UQ_EQUIPAJE_ETIQUETA");

                    b.ToTable("EQUIPAJE", "ventas");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.EscalaEntity", b =>
                {
                    b.Property<int>("IdEscala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_escala");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEscala"));

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("SYSTEM")
                        .HasColumnName("creado_por_usuario");

                    b.Property<int>("DuracionMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("duracion_min");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVO")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaHoraLlegada")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_hora_llegada");

                    b.Property<DateTime>("FechaHoraSalida")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_hora_salida");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_registro_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdAeropuerto")
                        .HasColumnType("integer")
                        .HasColumnName("id_aeropuerto");

                    b.Property<int>("IdVuelo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vuelo");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observaciones");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Puerta")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("puerta");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('00000001','hex')");

                    b.Property<string>("Terminal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("terminal");

                    b.Property<string>("TipoEscala")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("COMERCIAL")
                        .HasColumnName("tipo_escala");

                    b.HasKey("IdEscala");

                    b.HasIndex("IdAeropuerto");

                    b.HasIndex("IdVuelo", "Orden")
                        .IsUnique()
                        .HasDatabaseName("UQ_Escala_Vuelo_Orden");

                    b.ToTable("Escala", "vuelos", t =>
                        {
                            t.HasCheckConstraint("CK_Escala_Duracion", "duracion_min >= 0");

                            t.HasCheckConstraint("CK_Escala_Fechas", "fecha_hora_salida > fecha_hora_llegada");

                            t.HasCheckConstraint("CK_Escala_Orden", "orden >= 1");

                            t.HasCheckConstraint("CK_Escala_Tipo", "tipo_escala IN ('TECNICA','COMERCIAL')");
                        });
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.FacturaEntity", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFactura"));

                    b.Property<decimal>("CargoServicio")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("cargo_servicio");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("es_eliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime?>("FechaInhabilitacionUtc")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_inhabilitacion_utc");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<Guid>("GuidFactura")
                        .HasColumnType("uuid")
                        .HasColumnName("guid_factura");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdReserva")
                        .HasColumnType("integer")
                        .HasColumnName("id_reserva");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("MotivoInhabilitacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("motivo_inhabilitacion");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_factura");

                    b.Property<string>("ObservacionesFactura")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observaciones_factura");

                    b.Property<string>("OrigenCanalFactura")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("origen_canal_factura");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('00000001','hex')");

                    b.Property<string>("ServicioOrigen")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("servicio_origen");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("ValorIva")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("valor_iva");

                    b.HasKey("IdFactura");

                    b.HasIndex("GuidFactura")
                        .IsUnique()
                        .HasDatabaseName("UQ_FACTURA_GUID");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdReserva");

                    b.HasIndex("NumeroFactura")
                        .IsUnique()
                        .HasDatabaseName("UQ_FACTURA_NUMERO");

                    b.ToTable("Facturas", "ventas");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.PaisEntity", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pais");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPais"));

                    b.Property<string>("CodigoIso2")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("codigo_iso2");

                    b.Property<string>("CodigoIso3")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("codigo_iso3");

                    b.Property<string>("Continente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("continente");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminado");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdPais");

                    b.ToTable("Pais", "aero");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.PasajeroEntity", b =>
                {
                    b.Property<int>("IdPasajero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pasajero");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPasajero"));

                    b.Property<string>("ApellidoPasajero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_pasajero");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<string>("EmailContactoPasajero")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email_contacto_pasajero");

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_eliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVO")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTime?>("FechaNacimientoPasajero")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento_pasajero");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<string>("GeneroPasajero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("genero_pasajero");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<string>("ModificacionIp")
                        .HasColumnType("text")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasColumnType("text")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("NacionalidadPasajero")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nacionalidad_pasajero");

                    b.Property<string>("NombrePasajero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_pasajero");

                    b.Property<string>("NumeroDocumentoPasajero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero_documento_pasajero");

                    b.Property<string>("ObservacionesPasajero")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observaciones_pasajero");

                    b.Property<bool>("RequiereAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requiere_asistencia");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('00000001','hex')");

                    b.Property<string>("TelefonoContactoPasajero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono_contacto_pasajero");

                    b.Property<string>("TipoDocumentoPasajero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_documento_pasajero");

                    b.HasKey("IdPasajero");

                    b.HasIndex("IdCliente");

                    b.ToTable("Pasajero", "ventas");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.ReservaEntity", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_reserva");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("CodigoReserva")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_reserva");

                    b.Property<string>("ContactoEmail")
                        .HasColumnType("text")
                        .HasColumnName("contacto_email");

                    b.Property<string>("ContactoTelefono")
                        .HasColumnType("text")
                        .HasColumnName("contacto_telefono");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creado_por_usuario");

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("es_eliminado");

                    b.Property<string>("EstadoReserva")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado_reserva");

                    b.Property<DateTime?>("FechaCancelacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_cancelacion_utc");

                    b.Property<DateTime?>("FechaConfirmacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_confirmacion_utc");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInhabilitacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_inhabilitacion_utc");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<DateTime>("FechaReservaUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_reserva_utc");

                    b.Property<Guid>("GuidReserva")
                        .HasColumnType("uuid")
                        .HasColumnName("guid_reserva");

                    b.Property<int>("IdAsiento")
                        .HasColumnType("integer")
                        .HasColumnName("id_asiento");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdPasajero")
                        .HasColumnType("integer")
                        .HasColumnName("id_pasajero");

                    b.Property<int>("IdVuelo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vuelo");

                    b.Property<string>("ModificacionIp")
                        .HasColumnType("text")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasColumnType("text")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("text")
                        .HasColumnName("motivo_cancelacion");

                    b.Property<string>("MotivoInhabilitacion")
                        .HasColumnType("text")
                        .HasColumnName("motivo_inhabilitacion");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("OrigenCanalReserva")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origen_canal_reserva");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('00000001','hex')");

                    b.Property<string>("ServicioOrigen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("servicio_origen");

                    b.Property<decimal>("SubtotalReserva")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal_reserva");

                    b.Property<decimal>("TotalReserva")
                        .HasColumnType("numeric")
                        .HasColumnName("total_reserva");

                    b.Property<decimal>("ValorIva")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_iva");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdAsiento");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdPasajero");

                    b.HasIndex("IdVuelo");

                    b.ToTable("RESERVAS", "ventas");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.RolEntity", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("SYSTEM")
                        .HasColumnName("creado_por_usuario");

                    b.Property<string>("DescripcionRol")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion_rol");

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_eliminado");

                    b.Property<string>("EstadoRol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("ACT")
                        .HasColumnName("estado_rol");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_rol");

                    b.Property<Guid>("RolGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rol_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('00000001','hex')");

                    b.HasKey("IdRol");

                    b.HasIndex("NombreRol")
                        .IsUnique()
                        .HasDatabaseName("UQ_ROL_NOMBRE");

                    b.HasIndex("RolGuid")
                        .IsUnique()
                        .HasDatabaseName("UQ_ROL_GUID");

                    b.ToTable("ROL", "seg");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.UsuarioAppEntity", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("correo");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("SYSTEM")
                        .HasColumnName("creado_por_usuario");

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_eliminado");

                    b.Property<string>("EstadoUsuario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("ACT")
                        .HasColumnName("estado_usuario");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaUltimoLogin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_ultimo_login");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("password_salt");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('00000001','hex')");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.Property<Guid>("UsuarioGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdCliente");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("UsuarioGuid")
                        .IsUnique();

                    b.ToTable("USUARIO_APP", "seg");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.UsuarioRolEntity", b =>
                {
                    b.Property<int>("IdUsuarioRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuarioRol"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("SYSTEM")
                        .HasColumnName("creado_por_usuario");

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_eliminado");

                    b.Property<string>("EstadoUsuarioRol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("ACT")
                        .HasColumnName("estado_usuario_rol");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('00000001','hex')");

                    b.HasKey("IdUsuarioRol");

                    b.HasIndex("IdRol")
                        .HasDatabaseName("IX_USUARIOS_ROLES_ROL");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_USUARIOS_ROLES_USUARIO");

                    b.HasIndex("IdUsuario", "IdRol")
                        .IsUnique()
                        .HasDatabaseName("UQ_USUARIOS_ROLES_USR_ROL");

                    b.ToTable("USUARIOS_ROLES", "seg");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.VueloEntity", b =>
                {
                    b.Property<int>("IdVuelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_vuelo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVuelo"));

                    b.Property<int>("CapacidadTotal")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_total");

                    b.Property<string>("CodigoVuelo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_vuelo");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<int>("DuracionMin")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_min");

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoVuelo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_vuelo");

                    b.Property<DateTime>("FechaHoraLlegada")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_hora_llegada");

                    b.Property<DateTime>("FechaHoraSalida")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_hora_salida");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTime>("FechaRegistroUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<int>("IdAeropuertoDestino")
                        .HasColumnType("integer")
                        .HasColumnName("id_aeropuerto_destino");

                    b.Property<int>("IdAeropuertoOrigen")
                        .HasColumnType("integer")
                        .HasColumnName("id_aeropuerto_origen");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_base");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('00000001','hex')");

                    b.HasKey("IdVuelo");

                    b.HasIndex("IdAeropuertoDestino");

                    b.HasIndex("IdAeropuertoOrigen");

                    b.ToTable("Vuelo", "vuelos");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.AeropuertoEntity", b =>
                {
                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.CiudadEntity", "Ciudad")
                        .WithMany("Aeropuertos")
                        .HasForeignKey("IdCiudad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.PaisEntity", "Pais")
                        .WithMany("Aeropuertos")
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ciudad");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.AsientoEntity", b =>
                {
                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.VueloEntity", "Vuelo")
                        .WithMany("Asientos")
                        .HasForeignKey("IdVuelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.BoletoEntity", b =>
                {
                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.AsientoEntity", "Asiento")
                        .WithMany()
                        .HasForeignKey("IdAsiento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.FacturaEntity", "Factura")
                        .WithMany("Boletos")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.ReservaEntity", "Reserva")
                        .WithMany("Boletos")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.VueloEntity", "Vuelo")
                        .WithMany("Boletos")
                        .HasForeignKey("IdVuelo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asiento");

                    b.Navigation("Factura");

                    b.Navigation("Reserva");

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.CiudadEntity", b =>
                {
                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.PaisEntity", "Pais")
                        .WithMany("Ciudades")
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.ClienteEntity", b =>
                {
                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.CiudadEntity", "CiudadResidencia")
                        .WithMany()
                        .HasForeignKey("IdCiudadResidencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.PaisEntity", "PaisNacionalidad")
                        .WithMany("Clientes")
                        .HasForeignKey("IdPaisNacionalidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CiudadResidencia");

                    b.Navigation("PaisNacionalidad");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.EquipajeEntity", b =>
                {
                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.BoletoEntity", "Boleto")
                        .WithMany()
                        .HasForeignKey("IdBoleto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boleto");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.EscalaEntity", b =>
                {
                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.AeropuertoEntity", "Aeropuerto")
                        .WithMany()
                        .HasForeignKey("IdAeropuerto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.VueloEntity", "Vuelo")
                        .WithMany("Escalas")
                        .HasForeignKey("IdVuelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aeropuerto");

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.FacturaEntity", b =>
                {
                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.ClienteEntity", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.ReservaEntity", "Reserva")
                        .WithMany("Facturas")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.PasajeroEntity", b =>
                {
                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.ClienteEntity", "Cliente")
                        .WithMany("Pasajeros")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Pasajero_Cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.ReservaEntity", b =>
                {
                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.AsientoEntity", "Asiento")
                        .WithMany()
                        .HasForeignKey("IdAsiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.ClienteEntity", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.PasajeroEntity", "Pasajero")
                        .WithMany("Reservas")
                        .HasForeignKey("IdPasajero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.VueloEntity", "Vuelo")
                        .WithMany()
                        .HasForeignKey("IdVuelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asiento");

                    b.Navigation("Cliente");

                    b.Navigation("Pasajero");

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.UsuarioAppEntity", b =>
                {
                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.ClienteEntity", "Cliente")
                        .WithMany("UsuariosApp")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK_USUARIO_APP_CLIENTE");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.UsuarioRolEntity", b =>
                {
                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.RolEntity", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USUARIOS_ROLES_ROL");

                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.UsuarioAppEntity", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USUARIOS_ROLES_USUARIO");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.VueloEntity", b =>
                {
                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.AeropuertoEntity", "AeropuertoDestino")
                        .WithMany()
                        .HasForeignKey("IdAeropuertoDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microservicio.Vuelos.DataAccess.Entities.AeropuertoEntity", "AeropuertoOrigen")
                        .WithMany()
                        .HasForeignKey("IdAeropuertoOrigen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AeropuertoDestino");

                    b.Navigation("AeropuertoOrigen");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.CiudadEntity", b =>
                {
                    b.Navigation("Aeropuertos");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.ClienteEntity", b =>
                {
                    b.Navigation("Pasajeros");

                    b.Navigation("Reservas");

                    b.Navigation("UsuariosApp");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.FacturaEntity", b =>
                {
                    b.Navigation("Boletos");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.PaisEntity", b =>
                {
                    b.Navigation("Aeropuertos");

                    b.Navigation("Ciudades");

                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.PasajeroEntity", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.ReservaEntity", b =>
                {
                    b.Navigation("Boletos");

                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.RolEntity", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.UsuarioAppEntity", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("Microservicio.Vuelos.DataAccess.Entities.VueloEntity", b =>
                {
                    b.Navigation("Asientos");

                    b.Navigation("Boletos");

                    b.Navigation("Escalas");
                });
#pragma warning restore 612, 618
        }
    }
}
